<body>
	<div id="root"></div>
	<script src="https://unpkg.com/react@18.3.1/umd/react.development.js"></script>
	<script src="https://unpkg.com/react-dom@18.3.1/umd/react-dom.development.js"></script>
	<script src="https://unpkg.com/@babel/standalone@7.28.4/babel.js"></script>
	<script src="https://unpkg.com/react-error-boundary@1.2.5/dist/umd/react-error-boundary.js"></script>
	<script type="text/babel">
		const ErrorBoundary = ReactErrorBoundary.ErrorBoundary;
		/*
		class ErrorBoundary extends React.Component {
			state = { error: null };
			static getDerivedStateFromError(error) {
				return { error };
			}
			render() {
				const { error } = this.state;
				if (error) {
					return <this.props.FallbackComponent error={error} />;
				}
				return this.props.children;
			}
		}
        */ // normally use third party library i.e.react error boundary
		function ErrorFallback({ error }) {
			return (
				<div>
					<p>Something went wrong:</p>
					<pre>{error.message}</pre>
				</div>
			);
		}
		function Bomb() {
			throw new Error('KABOOM ðŸ’¥');
		}

		function App() {
			const [explode, setExplode] = React.useState(false);
			return (
				<ErrorBoundary FallbackComponent={ErrorFallback}>
					<div>
						<div>
							<button onClick={() => setExplode(true)}> ðŸ’£ </button>
						</div>
						<div>
							<ErrorBoundary FallbackComponent={ErrorFallback}>
								{explode ? <Bomb /> : 'Push the button Max!'}
							</ErrorBoundary>
						</div>
					</div>
				</ErrorBoundary>
			);
		}
		const root = ReactDOM.createRoot(document.getElementById('root'));
		root.render(<App />);
	</script>
</body>
